name: Build

on:
  push:
    paths:
      - '!README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: '18.x'
      - name: Install pnpm
        uses: pnpm/action-setup@master
        with:
          version: 7
      - name: Install dependencies
        run: pnpm i
      - name: Build README.md
        run: pnpm run build
      - name: Commit README.md
        run: |
          git config user.name builder-bot
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || git commit \
            -am ":sparkles: feat(README.md): README.md was built" \
            -am "Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          git push origin main
